-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 00:25:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forja_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forja_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forja_db` DEFAULT CHARACTER SET utf8 ;
USE `forja_db` ;

-- -----------------------------------------------------
-- Table `forja_db`.`imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`imagenes` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`imagenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`colores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`colores` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`colores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`tallesLetra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`tallesLetra` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`tallesLetra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` CHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`tallesNum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`tallesNum` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`tallesNum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`categorias` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`productos` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `precio` DECIMAL NOT NULL,
  `descuento` TINYINT(2) NULL,
  `envio` TINYINT(1) NULL,
  `talleNum_id` INT NULL,
  `talleLetra_id` INT NULL,
  `color_id` INT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `categoria_id` INT NOT NULL,
  `imagen_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_imagenes_id_idx` (`imagen_id` ASC) VISIBLE,
  INDEX `Fk_tallesLetra_id_idx` (`talleLetra_id` ASC) VISIBLE,
  INDEX `Fk_tallesNum_idx` (`talleNum_id` ASC) VISIBLE,
  INDEX `FK_categoria_id_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `FK_colores_id_idx` (`color_id` ASC) VISIBLE,
  CONSTRAINT `FK_imagenes_id`
    FOREIGN KEY (`imagen_id`)
    REFERENCES `forja_db`.`imagenes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_colores_id`
    FOREIGN KEY (`color_id`)
    REFERENCES `forja_db`.`colores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_tallesLetra_id`
    FOREIGN KEY (`talleLetra_id`)
    REFERENCES `forja_db`.`tallesLetra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_tallesNum`
    FOREIGN KEY (`talleNum_id`)
    REFERENCES `forja_db`.`tallesNum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_categoria_id`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `forja_db`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `userName` VARCHAR(50) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `subscripcion_forja` TINYINT(1) NULL,
  `telefono` INT NULL,
  `imagen` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`facturas` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`facturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  `total` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `FK_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `forja_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`medios_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`medios_de_pago` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`medios_de_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forja_db`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forja_db`.`ventas` ;

CREATE TABLE IF NOT EXISTS `forja_db`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `producto_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `medio_de_pago` INT NOT NULL,
  `factura_id` INT NOT NULL,
  `total` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_factura_id_idx` (`factura_id` ASC) VISIBLE,
  INDEX `FK_ventas_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `FK_medio_de_pago_id_idx` (`medio_de_pago` ASC) VISIBLE,
  INDEX `FK_producto_id_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `FK_factura_id`
    FOREIGN KEY (`factura_id`)
    REFERENCES `forja_db`.`facturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ventas_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `forja_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_pago_id`
    FOREIGN KEY (`medio_de_pago`)
    REFERENCES `forja_db`.`medios_de_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `forja_db`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
